version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: backend_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root_password
      DB_NAME: my_database
    depends_on:
      - db

  frontend:
    build: ./frontend/dashboard-frontend
    container_name: frontend_app
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/dashboard-frontend:/app
      - /app/node_modules
    # ELIMINADO: La línea 'command: sh -c "npm install && ng serve..."'
    depends_on:
      - backend

volumes:
  mysql_data: